### PR TITLE
folder parsing

### PR DESCRIPTION
**Pull request by sdepold**
i guess formatting is far from perfect, but the functionality is working :) this pull request allows the following usage

``` console
// define a source folder and skip the target folder => target folder === './docs'
dox-foundation --source ./lib
// define a source and a target folder
dox-foundation --source ./lib --target ./documentation
```

### CODE REVIEW

**Comment by sdepold** [comment]
guess i will go on working on this thing. even the html structure isn't very nice right now

**Comment by mattmcmanus** [comment]
Hey @sdepold, this is some solid work. Thank you so much. I haven't had a chance to try it out yet. Once I get a minute I will and most likely will pull it in. Hopefully sometime today.

**Comment by sdepold** [comment]
the html structure is a bit better now. i guess we should add a button, which hides and shows the navigation.

**Comment by sdepold** [comment]
an index.html would be nice (i may add it later today)

**Comment by mattmcmanus** [comment]
Looking into this this morning. I've never used walk before so I just want familiarize myself with it.

**Comment by sdepold** [comment]
is it morning for you atm? ^^ it's 4pm here :D

**Comment by mattmcmanus** [comment]
Nice! I'm in EST so it's now about lunch time. 

I've got a bunch of scattered thoughts:
1. I like the walk module and what you've done with it. I pulled down your code and pushed it a new branch with some changes: https://github.com/punkave/dox-foundation/tree/pr/5. Before I pull this in, I wanted to add some basic directory ignoring support. I set it up so that it ignores js files by default and has a default list of of folders to ignore that can be overridden. I've never changed someone's pull request before but I image if you pull in that branch to yours it will work. 
2. I dont mind doing this later because it's not super pressing, but I think it would be nice to breakdown the code in the `/bin` file into separate functions living in some sort of `folders.js` or `structure.js` file in `/lib`

One final thought/question: Do you think it's better to create individual html files for each file, then an index or to simply create one big file? I was leaning towards one file but I'm open to suggestions.

**Comment by sdepold** [comment]
@1: like
@2: like
@question: imho multiple files are quite ok. however there should be an index.html as well as some styling to the file listing

**Comment by sdepold** [comment]
the last commit made the whole thing prettier :) i will add highlighting of the current file later this day

**Comment by sdepold** [comment]
separated logic into functions + some styling

**Comment by sdepold** [comment]
yeah index.html ftw. this was most likely my last commit for this story :)

**Comment by audreyfeldroy** [comment]
Wow! Looking forward to this feature.

**Comment by sdepold** [comment]
btw. this is how the index.html looks like: http://cl.ly/image/3o2k0J0H3h3f
and this is how a generated code file looks like: http://cl.ly/image/3N2v2J2I032N

**Comment by mattmcmanus** [comment]
Fantastic! This is some solid work @sdepold. Very much appreciated. I'll deploy this to npm now

**Comment by sdepold** [comment]
yeah :)

**Pull request merged**
