### PR TITLE
fix: Use `doctype html` instead of `doctype 5`

### PR DESCRIPTION
**Pull request by jtrussell**
`doctype 5` is deprecated in favor of `doctype html`. Just installed a fresh version of `grunt-dox` and generation failed complaining of this doctype.

### CODE REVIEW

**Comment by randallagordon** [comment]
:+1:

**Comment by cliffano** [comment]
+1 for merging this pull request.
I'm using dox-foundation for a number of modules build, which at the moment breaks all over the places due to dox-foundation's use of 'doctype 5' being replaced with 'doctype html' in jade.

@punkave Any chance to merge this PR? Thanks in advance.

**Comment by mattmcmanus** [comment]
Thanks for this. I just merged in #50 and I'm verifying everything works. I'll close this ticket once I push a new version out.

**Comment by jtrussell** [comment]
Thanks!

**Comment by mattmcmanus** [comment]
Alrighty! `0.5.5` is out and working. Thanks for the help!

**Pull request closed without merging**
