### PR TITLE
Sets word-break for nav links

### PR DESCRIPTION
**Pull request by jeremyckahn**
For nav links that run long in Webkit, there can be an overlap:

Overlap.  

Firefox does not have this problem.  This patch adds a `word-break` rule to wrap the characters:

Wrapped characters

It's not super pretty, but it's an improvement.  If merged, please update grunt-dox as well to use the latest version of dox-foundation.

### CODE REVIEW

**Comment by mattmcmanus** [comment]
Hey @jeremyckahn, Thanks for the pull request! It looks like your images aren't working. Could you try again? I'd love to see what you're seeing

**Comment by jeremyckahn** [comment]
Sure, sorry about the images before.  Sometimes Dropbox-hosted images don't show up for everyone.

Here's how it looks before the fix:

Broken :(

And here's how it looks with this patch:

Fixed :)

**Comment by mattmcmanus** [comment]
Looks good enough for me for now. It may be worth considering going forward making the column bigger or doing something a little fancier like ellipsing until hovered or something.

**Comment by jeremyckahn** [comment]
Personally, I think the column width is good as it is.  I think a more flexible approach would be to truncate the text, as you suggested, with ellipsizing.

**Comment by jeremyckahn** [comment]
Can you please increment the package minor versions for dox-foundation and grunt-dox so I can get the latest version from npm?  Since the version was kept at 0.4.7 for this Pull Request, it doesn't seem that npm is referencing HEAD anymore.

I probably should have done that in my Pull Request, I will try to do so in the future.

**Comment by mattmcmanus** [comment]
Oh man. Total brain fart over here. I thought I had already done that. I pushed 0.4.8 to npm of dox-foundation. Grunt-dox should pick up this new version

**Pull request merged**
